### PR TITLE
Automatic deps

### PR DESCRIPTION
**Pull request by neutrinoceros**
this is an attempt to automate dependencies checking within `src/makefile`

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@jannisteunissen , if you have any idea how to make this work... otherwise I'll ask the IT section at my lab

**Comment by jannisteunissen** [comment]
I'm not sure whether it would be a good idea to always run the script, since the script might not work on some systems. However, we could make it easier for people to run it, since now you have to copy/paste the results. What do you think?

**Comment by neutrinoceros** [comment]
If it does not work on some systems, it might be worth improving on it, but I have no idea which system this could fail on.

We can also make it easier to use. For example, we could make the script itself optionnaly update the makefile instead of printing out the depedencies.

What I was able to accomplish yesterday was to make the travis CI runner recompile from scratch each time it runs, so now commits that are missing the update will be caught as "build fails", which is already an improvement.

**Comment by neutrinoceros** [comment]
solved in branch `nocachetravis`

**Pull request closed without merging**
