### PR TITLE
Python tools edit

### PR DESCRIPTION
**Pull request by FinMacDov**
Mostly fixed pep8 issues for polyplot class. Added title option for polyplot (useful for sub plotting) and added log_info to reduce the number of print statements to speed up the code.

### CODE REVIEW

**Comment by n-claes** [comment]
Looks great! There is one tiny conflict with `master` though, I think you used tabs somewhere where there were spaces previously (and git marks this as a conflict for some reason) so it's a trivial fix. Only I can't resolve it directly without merging the branch into `master`, so that depends if you want to add more changes or features in the near future?
Otherwise I think it's best to leave this pull request open and then merge everything using one single commit after you've added those changes (to avoid having a lot of pull requests cluttering the commit list)

**Comment by FinMacDov** [comment]
Sorry about that, I was wondering why a conflict had been raised. I have fixed the rest of the pep8 issues. The next changes I plan are:
1) to add to the documentation.
2) Give some description of what the expected inputs are for the classes and functions. 
3) I want to change var names that conflict with inbuilt functions python, e.g. inputs called min, max and type.      

I don't think I'll be making these changes soon though.

**Comment by FinMacDov** [comment]
Are you both happy with this pull request as is or do you want me to remove the PEP8 fixes?

**Comment by neutrinoceros** [comment]
Other than providing my git/python "expertise", I will not review the PR because I don't know the code discussed.

## about the merging strategy:

* I would advise that you rebase your branch to the latest version of master, and if you don't mind, remove the commits about PEP8'ing in the process.
While rebasing, you'll have to change the commits that cause conflicts, so at the end of the process, you'll get a clean and mergeable branch.
If you are not comfortable with the process just ask.
* In my opinion it's good to have multiple PRs to clearly separate your different contributions : code styling and feature additions should ideally be done separately

## about the PR itself:

I'm more than in favor of renaming variables whose name correspond to builtin functunalities of Python ("dir" is all over the place...) But it's not always a good idea if it breaks existing user code, so maybe refrain from renaming the functions and their arguments. I still believe it's for the best if it happens at some point, but we'll need to warn users *before* it does.

**Comment by n-claes** [comment]
Completely agree with @neutrinoceros's comment, both on merging strategy and PR. Regarding the review, I went through it and at first glance it seems fine as it does not make any changes to previous methods (and I assume the newly added method is tested).

The thing is, the framework for datfile processing was implemented from scratch by me, but the vtk readers are directly imported from the 'old' tools and the BHAC code, I did not write these myself (and I'm actually not sure who did). I merely made them compatible with python 3 and removed old/unused methods. Ideally like 90% of the vtk methods need refactoring and clean-up (and some of them just have to be rewritten), but because they're quite extended it's not a minor undertaking.

As of right now that's rather a low priority (at least for me), as we have 1) the datfile framework which is quite convenient and 2) the upcoming yt frontend that can do everything the vtk readers can and more. Because most people probably use applications like VisIt or Paraview for vtk filetypes anyway I'm not going to spend time on the vtk reader (unless there are bugs) in the near future. But if you have extensions or suggestions for those, feel free to drop a PR!

For this one, I would say follow @neutrinoceros's merging strategy and then you can merge it.

**Comment by FinMacDov** [comment]
I agree with what you both said about PR strategy and to remove the pep8 fixes I can revert the PR to comit 56de106. Although, my counter-argument would be that from what @n-claes has said is that this part of the code will become obsolete or completely rewritten and as it is not a high priority, does it not make sense to accept the PR requested as is because it’s an improvement on the code that is there and what I have "fixed" is unlikely to changed soon.

Is there any other parts of the python tools that I can help with?

**Comment by n-claes** [comment]
@FinMacDov I resolved the conflict in `amrplot` and going to merge this with `master` when the automatic tests pass.
I'm gonna leave the pep-8 discussion as-is, on the basis that 1) the changes you proposed actually improve the readability of that piece of code by quite a lot and 2) there are no method names or arguments removed/modified, so it should not break existing user code.

**Pull request merged**
